/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ThemisVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOM"
      | "LOSS_CAP_BPS"
      | "VAULT_CAP"
      | "WALLET_CAP"
      | "admin"
      | "agentAllocation"
      | "agentDailyDeployed"
      | "agentDailyPnl"
      | "agentDayStart"
      | "agentSidelined"
      | "allocate"
      | "allocator"
      | "deposit"
      | "depositedBy"
      | "liquidReserve"
      | "pause"
      | "paused"
      | "setAllocator"
      | "settle"
      | "shareBalances"
      | "sharePrice"
      | "sidelineAgent"
      | "totalAssets"
      | "totalDeployed"
      | "totalShares"
      | "unpause"
      | "unsidelineAgent"
      | "usdc"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentSidelined"
      | "Allocated"
      | "Deposited"
      | "Settled"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(functionFragment: "BPS_DENOM", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "LOSS_CAP_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "VAULT_CAP", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "WALLET_CAP",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "agentAllocation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agentDailyDeployed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agentDailyPnl",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agentDayStart",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agentSidelined",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allocate",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "allocator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositedBy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidReserve",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAllocator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settle",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "shareBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sharePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sidelineAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalDeployed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalShares",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unsidelineAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "BPS_DENOM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "LOSS_CAP_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "VAULT_CAP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WALLET_CAP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentAllocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentDailyDeployed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentDailyPnl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentDayStart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentSidelined",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allocate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allocator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositedBy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAllocator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "shareBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sharePrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sidelineAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDeployed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unsidelineAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace AgentSidelinedEvent {
  export type InputTuple = [agent: AddressLike, dailyPnl: BigNumberish];
  export type OutputTuple = [agent: string, dailyPnl: bigint];
  export interface OutputObject {
    agent: string;
    dailyPnl: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AllocatedEvent {
  export type InputTuple = [
    agent: AddressLike,
    amount: BigNumberish,
    cycleId: BigNumberish
  ];
  export type OutputTuple = [agent: string, amount: bigint, cycleId: bigint];
  export interface OutputObject {
    agent: string;
    amount: bigint;
    cycleId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    amount: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [wallet: string, amount: bigint, shares: bigint];
  export interface OutputObject {
    wallet: string;
    amount: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettledEvent {
  export type InputTuple = [
    agent: AddressLike,
    pnl: BigNumberish,
    newTotalAssets: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    pnl: bigint,
    newTotalAssets: bigint
  ];
  export interface OutputObject {
    agent: string;
    pnl: bigint;
    newTotalAssets: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    wallet: AddressLike,
    shares: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [wallet: string, shares: bigint, amount: bigint];
  export interface OutputObject {
    wallet: string;
    shares: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ThemisVault extends BaseContract {
  connect(runner?: ContractRunner | null): ThemisVault;
  waitForDeployment(): Promise<this>;

  interface: ThemisVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOM: TypedContractMethod<[], [bigint], "view">;

  LOSS_CAP_BPS: TypedContractMethod<[], [bigint], "view">;

  VAULT_CAP: TypedContractMethod<[], [bigint], "view">;

  WALLET_CAP: TypedContractMethod<[], [bigint], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  agentAllocation: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  agentDailyDeployed: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  agentDailyPnl: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  agentDayStart: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  agentSidelined: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  allocate: TypedContractMethod<
    [agent: AddressLike, amount: BigNumberish, cycleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  allocator: TypedContractMethod<[], [string], "view">;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  depositedBy: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  liquidReserve: TypedContractMethod<[], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  setAllocator: TypedContractMethod<
    [_allocator: AddressLike],
    [void],
    "nonpayable"
  >;

  settle: TypedContractMethod<
    [agent: AddressLike, pnl: BigNumberish],
    [void],
    "nonpayable"
  >;

  shareBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  sharePrice: TypedContractMethod<[], [bigint], "view">;

  sidelineAgent: TypedContractMethod<
    [agent: AddressLike],
    [void],
    "nonpayable"
  >;

  totalAssets: TypedContractMethod<[], [bigint], "view">;

  totalDeployed: TypedContractMethod<[], [bigint], "view">;

  totalShares: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  unsidelineAgent: TypedContractMethod<
    [agent: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<[shares: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOSS_CAP_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VAULT_CAP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WALLET_CAP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agentAllocation"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentDailyDeployed"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentDailyPnl"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentDayStart"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentSidelined"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "allocate"
  ): TypedContractMethod<
    [agent: AddressLike, amount: BigNumberish, cycleId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allocator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositedBy"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidReserve"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setAllocator"
  ): TypedContractMethod<[_allocator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settle"
  ): TypedContractMethod<
    [agent: AddressLike, pnl: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shareBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "sharePrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "sidelineAgent"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalAssets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalDeployed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalShares"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unsidelineAgent"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[shares: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AgentSidelined"
  ): TypedContractEvent<
    AgentSidelinedEvent.InputTuple,
    AgentSidelinedEvent.OutputTuple,
    AgentSidelinedEvent.OutputObject
  >;
  getEvent(
    key: "Allocated"
  ): TypedContractEvent<
    AllocatedEvent.InputTuple,
    AllocatedEvent.OutputTuple,
    AllocatedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "Settled"
  ): TypedContractEvent<
    SettledEvent.InputTuple,
    SettledEvent.OutputTuple,
    SettledEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "AgentSidelined(address,int256)": TypedContractEvent<
      AgentSidelinedEvent.InputTuple,
      AgentSidelinedEvent.OutputTuple,
      AgentSidelinedEvent.OutputObject
    >;
    AgentSidelined: TypedContractEvent<
      AgentSidelinedEvent.InputTuple,
      AgentSidelinedEvent.OutputTuple,
      AgentSidelinedEvent.OutputObject
    >;

    "Allocated(address,uint256,uint256)": TypedContractEvent<
      AllocatedEvent.InputTuple,
      AllocatedEvent.OutputTuple,
      AllocatedEvent.OutputObject
    >;
    Allocated: TypedContractEvent<
      AllocatedEvent.InputTuple,
      AllocatedEvent.OutputTuple,
      AllocatedEvent.OutputObject
    >;

    "Deposited(address,uint256,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "Settled(address,int256,uint256)": TypedContractEvent<
      SettledEvent.InputTuple,
      SettledEvent.OutputTuple,
      SettledEvent.OutputObject
    >;
    Settled: TypedContractEvent<
      SettledEvent.InputTuple,
      SettledEvent.OutputTuple,
      SettledEvent.OutputObject
    >;

    "Withdrawn(address,uint256,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
