/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TraceAnchorInterface extends Interface {
  getFunction(nameOrSignature: "anchor"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TraceAnchored"): EventFragment;

  encodeFunctionData(
    functionFragment: "anchor",
    values: [AddressLike, BytesLike, string]
  ): string;

  decodeFunctionResult(functionFragment: "anchor", data: BytesLike): Result;
}

export namespace TraceAnchoredEvent {
  export type InputTuple = [
    agent: AddressLike,
    hash: BytesLike,
    cid: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    hash: string,
    cid: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    agent: string;
    hash: string;
    cid: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TraceAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): TraceAnchor;
  waitForDeployment(): Promise<this>;

  interface: TraceAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchor: TypedContractMethod<
    [agent: AddressLike, hash: BytesLike, cid: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchor"
  ): TypedContractMethod<
    [agent: AddressLike, hash: BytesLike, cid: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "TraceAnchored"
  ): TypedContractEvent<
    TraceAnchoredEvent.InputTuple,
    TraceAnchoredEvent.OutputTuple,
    TraceAnchoredEvent.OutputObject
  >;

  filters: {
    "TraceAnchored(address,bytes32,string,uint256)": TypedContractEvent<
      TraceAnchoredEvent.InputTuple,
      TraceAnchoredEvent.OutputTuple,
      TraceAnchoredEvent.OutputObject
    >;
    TraceAnchored: TypedContractEvent<
      TraceAnchoredEvent.InputTuple,
      TraceAnchoredEvent.OutputTuple,
      TraceAnchoredEvent.OutputObject
    >;
  };
}
