/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IThemisRegistryView__factory } from "./IThemisRegistryView__factory";
export { TraceAnchor__factory } from "./TraceAnchor__factory";
