/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IThemisRegistryView,
  IThemisRegistryViewInterface,
} from "../../../contracts/TraceAnchor.sol/IThemisRegistryView";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
    ],
    name: "stats",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
      {
        internalType: "int128",
        name: "",
        type: "int128",
      },
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IThemisRegistryView__factory {
  static readonly abi = _abi;
  static createInterface(): IThemisRegistryViewInterface {
    return new Interface(_abi) as IThemisRegistryViewInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IThemisRegistryView {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IThemisRegistryView;
  }
}
