// ABIs are generated by apps/contracts deploy script and copied here
export const ThemisVaultABI: unknown[] = [];
export const ThemisRegistryABI: unknown[] = [];
export const TraceAnchorABI: unknown[] = [];
