/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IThemisRegistryView } from "./IThemisRegistryView";
export type { TraceAnchor } from "./TraceAnchor";
