/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  TraceAnchor,
  TraceAnchorInterface,
} from "../../contracts/TraceAnchor";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "cid",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "TraceAnchored",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "cid",
        type: "string",
      },
    ],
    name: "anchor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610319806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063a014b31c14610030575b600080fd5b61004a600480360381019061004591906101a9565b61004c565b005b8373ffffffffffffffffffffffffffffffffffffffff167fab1071889c232d06bc2defbb55e9f8a2972dfa6156537696248be457996663c68484844260405161009894939291906102a3565b60405180910390a250505050565b600080fd5b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006100db826100b0565b9050919050565b6100eb816100d0565b81146100f657600080fd5b50565b600081359050610108816100e2565b92915050565b6000819050919050565b6101218161010e565b811461012c57600080fd5b50565b60008135905061013e81610118565b92915050565b600080fd5b600080fd5b600080fd5b60008083601f84011261016957610168610144565b5b8235905067ffffffffffffffff81111561018657610185610149565b5b6020830191508360018202830111156101a2576101a161014e565b5b9250929050565b600080600080606085870312156101c3576101c26100a6565b5b60006101d1878288016100f9565b94505060206101e28782880161012f565b935050604085013567ffffffffffffffff811115610203576102026100ab565b5b61020f87828801610153565b925092505092959194509250565b6102268161010e565b82525050565b600082825260208201905092915050565b82818337600083830152505050565b6000601f19601f8301169050919050565b6000610269838561022c565b935061027683858461023d565b61027f8361024c565b840190509392505050565b6000819050919050565b61029d8161028a565b82525050565b60006060820190506102b8600083018761021d565b81810360208301526102cb81858761025d565b90506102da6040830184610294565b9594505050505056fea2646970667358221220a44b031acb178eacb50045bb69c750c97d6548aae5dd0a46ecd78cb92561079364736f6c63430008180033";

type TraceAnchorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TraceAnchorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TraceAnchor__factory extends ContractFactory {
  constructor(...args: TraceAnchorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TraceAnchor & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): TraceAnchor__factory {
    return super.connect(runner) as TraceAnchor__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TraceAnchorInterface {
    return new Interface(_abi) as TraceAnchorInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): TraceAnchor {
    return new Contract(address, _abi, runner) as unknown as TraceAnchor;
  }
}
